language: python
python:
- 3.5

services:
- docker

env:  
- DB=postgresql  

before_script:
- pip install psycopg2
- pip install sqlalchemy
- pip install pycurl
- pip install isodate
- pip install json-rpc
- pip install psutil
- pip install pycurl
- sudo apt-get -qq update
- sudo /etc/init.d/postgresql stop
- sudo apt-get install -y postgresql-9.4
- sudo apt-get install -y postgresql-contrib-9.4 postgresql-plpython-9.4
- cd docker
# docker-compose up -d
# docker-compose ps
- cd ..
- psql -c "CREATE ROLE admin WITH PASSWORD 'admin' CREATEDB;" -U postgres
- psql -c 'create database xmusic;' -U postgres
- psql -U postgres -d xmusic -a -f doc/db.sql

script:
- cd daemon/unittest
- python3 test.py
#  python3 dbservicetestcase.py
# sudo netstat -apn |grep 5432
# sudo netstat -apn |grep 2345
# docker exec -it xmusic-db bash -c "ps auxw | grep post"
# docker exec -it xmusic-db bash -c "find / -name .s.PGSQL.5432 -ls"
# docker exec -it xmusic-db bash -c "cd usr;ls;cd local;ls;cd var;ls;cd postgres;ls"
# docker exec -it xmusic-db bash -c "psql -l -U postgres"
- psql xmusic -c 'select name from providers;' -U postgres
- psql -l -U postgres
