language: python
python:
- 3.6

services:
- postgresql

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5

before_script:
- pip install psycopg2
- pip install sqlalchemy
- pip install pycurl
- pip install isodate
- pip install json-rpc
- pip install psutil
- pip install pycurl
# sudo apt-get -qq update
# sudo /etc/init.d/postgresql stop
# sudo apt-get install -y postgresql-9.4
# sudo apt-get install -y postgresql-contrib-9.4 postgresql-plpython-9.4
- sudo -u postgres createuser -s -d -l admin
- psql -c "alter user admin login;" -U postgres
- psql -c 'CREATE DATABASE xmusic' -U postgres
- psql -U postgres -d xmusic -a -f doc/db.sql

script:
- cd daemon/unittest
- python3 dbservicetestcase.py
- python3 albumrepotestcase.py
- python3 dbservicetestcase.py
- python3 trackrepotestcase.py
