language: python
python:
- 3.5

services:
- docker

before_script:
- pip install psycopg2
- pip install sqlalchemy
- pip install pycurl
- pip install isodate
- pip install json-rpc
- pip install psutil
- pip install pycurl
- cd docker
- docker-compose up -d
- docker-compose ps
- cd ..

script:
- sudo netstat -apn |grep 5432
- sudo netstat -apn |grep 2345
- docker exec -t "xmusic-db" bash -c "ls"
- ls
- psql xmusic -U admin
- select name from providers;
- \d
