language: python
python:
- 3.5

services:
- xmusic-daemon
- xmusic-db

before_script:
- pip install -r requirements.txt
- pip install psycopg2
- pip install sqlalchemy
- pip install pycurl
- pip install isodate
- pip install json-rpc
- pip install psutil
- pip install pycurl

script:
- docker exec xmusic-daemon python3 unittest/test.py