language: python
python:
- 3.5

services:
- docker

before_script:
- pip install psycopg2
- pip install sqlalchemy
- pip install pycurl
- pip install isodate
- pip install json-rpc
- pip install psutil
- pip install pycurl
- pwd
- docker build - < docker/xmusic-daemon/Dockerfile
- docker build - < docker/xmusic-db/Dockerfile
- docker-compose up -d
- docker-compose ps
- cd ..

script:
- cd daemon/unittest
- python3 test.py
- python3 dbservicetestcase.py
- sudo netstat -apn |grep 5432
- sudo netstat -apn |grep 2345
- docker exec -it "xmusic-db" bash -c "psql xmusic -U admin"
- ls
- psql xmusic -U admin
- select name from providers;
- \d
