language: python
python:
- 3.5

services:
- docker
- postgresql

before_script:
- pip install psycopg2
- pip install sqlalchemy
- pip install pycurl
- pip install isodate
- pip install json-rpc
- pip install psutil
- pip install pycurl
- cd docker
- docker-compose up -d
- docker-compose ps
- cd ..

script:
- cd daemon/unittest
- python3 test.py
- python3 dbservicetestcase.py
- sudo netstat -apn |grep 5432
- sudo netstat -apn |grep 2345
- docker exec -it xmusic-db bash -c "ps auxw | grep post"
- docker exec -it xmusic-db bash -c "find / -name .s.PGSQL.5432 -ls"
- docker exec -it xmusic-db bash -c "cd /usr/local/var/postgres"
- docker exec -it xmusic-db bash -c "pwd"
- docker exec -it xmusic-db bash -c "ls"
- psql -l -U postgres
