language: python
python:
- 3.5

services:
- docker
- postgresql

before_script:
- pip install psycopg2
- pip install sqlalchemy
- pip install pycurl
- pip install isodate
- pip install json-rpc
- pip install psutil
- pip install pycurl
- cd docker
- docker-compose up -d
- docker-compose ps
- cd ..

script:
- cd daemon/unittest
- ls
- pwd
- python3 dbservicetestcase.py
