version: '2'
services:
    xmusic-db:
        container_name: xmusic-db
        build:
            context: ../
            dockerfile: docker/xmusic-db/Dockerfile
        image: postgres:xmusic-db
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=xmusic
    xmusic-mq:
        container_name: xmusic-mq
        image: webcenter/activemq:latest
        environment:
                - ACTIVEMQ_ENABLED_SCHEDULER=true
        ports:
                - 8161:8161
    xmusic-daemon:
        container_name: xmusic-daemon
        build:
            context: .
            dockerfile: xmusic-daemon/Dockerfile
        image: python:xmusic-daemon
        depends_on:
            - xmusic-db
            - xmusic-mq
        links:
            - xmusic-db:xmusic-db
            - xmusic-mq:xmusic-mq
        volumes:
            - ../daemon:/var/xmusic
        ports:
            - 50000:50000
        working_dir: /var/xmusic
        command: python3 xmusic.py
